### ISSUE TITLE
to.owl.carousel not working when dots disabled

### ISSUE THREAD

**Issue by dwbrito** [OwlFonk/OwlCarousel2#687]
When settings dots to false, 'to.owl.carousel' doesn't work, throwing error:
 Uncaught TypeError: Cannot read property 'start' of undefinedowl.carousel.js:2960 Navigation.tojquery.min.js:2 m.extend.proxy.m.isFunction.eowl.carousel.js:1443 (anonymous function)jquery.min.js:2 m.extend.proxy.m.isFunction.ejquery.min.js:3 m.event.dispatchjquery.min.js:3 m.event.add.r.handlejquery.min.js:3 m.event.triggerjquery.min.js:3 (anonymous function)jquery.min.js:2 m.extend.eachjquery.min.js:2 m.fn.m.eachjquery.min.js:3 m.fn.extend.triggerpen.js:28 (anonymous function)jquery.min.js:3 m.event.dispatchjquery.min.js:3 m.event.add.r.handle

Example (click on an image):
http://codepen.io/anon/pen/GgvGOe

**Comment by judewang** [comment]
@dwbrito Thank you for finding this bug! You saved my weekend, I can just hide the dots created by carousel and use my own dots, thanks!

**Comment by MichielBijl** [comment]
This should be fixed pronto. Just wasted about two hours on this…

**Comment by MichielBijl** [comment]
And it's related to: https://github.com/smashingboxes/OwlCarousel2/issues/166

**Comment by leecollings** [comment]
This still doesn't look like it's been fixed... there must be a better solution than to just hide the dots
